---
- name: Deploy ClickHouse, Vector, Lighthouse
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install common dependencies (curl, gnupg, etc.)
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: true

- name: Install Clickhouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Restart ClickHouse
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: Add ClickHouse GPG key
      ansible.builtin.apt_key:
        url: "https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key"
        state: present

    - name: Add ClickHouse repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.clickhouse.com/deb stable main"
        state: present
        filename: clickhouse.list

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install ClickHouse packages
      ansible.builtin.apt:
        name: "{{ clickhouse_packages }}"
        state: present
        force_apt_get: true

    - name: Ensure ClickHouse service is enabled and started
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: true

    # - name: Verify ClickHouse is running
    #   ansible.builtin.command: clickhouse-client --query "SELECT version()"
    #   register: clickhouse_version_check
    #   ignore_errors: true

    - name: Display ClickHouse version
      ansible.builtin.debug:
        var: clickhouse_version_check.stdout

    - name: Copy ClickHouse config
      ansible.builtin.template:
        src: templates/clickhouse/config.xml.j2
        dest: /etc/clickhouse-server/config.xml
        owner: clickhouse
        group: clickhouse
        mode: "0640"

    - name: Copy ClickHouse users
      ansible.builtin.template:
        src: templates/clickhouse/users.xml.j2
        dest: /etc/clickhouse-server/users.xml
        owner: clickhouse
        group: clickhouse
        mode: "0640"
      notify: Restart ClickHouse

    - name: Create database
      ansible.builtin.command: "clickhouse-client --host {{ ansible_host }} -q 'CREATE DATABASE IF NOT EXISTS logs;'"
      register: create_db
      failed_when: 
        - create_db.rc != 0 and create_db.rc !=82
        - "'already exists' not in create_db.stderr"
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Restart Vector
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: false
        name: vector.service
        state: restarted

  tasks:
    - name: Create vector work directory
      ansible.builtin.file:
        path: "{{ vector_workdir }}"
        state: directory
        mode: "0755"

    - name: Get Vector distrib
      ansible.builtin.copy:
        src: templates/0.47.0-1_amd64.deb
        dest: "{{ vector_workdir }}/vector-0.47.0-1_amd64.deb"
        mode: "0644"

    - name: Install Vector
      become: true
      ansible.builtin.apt:
        deb: "{{ vector_workdir }}/vector-0.47.0-1_amd64.deb"

    - name: Check Vector installation
      ansible.builtin.command: vector --version
      register: var_vector
      failed_when: var_vector.rc != 0
      changed_when: var_vector.rc == 0

    - name: Deploy Vector config
      ansible.builtin.template:
        src: templates/vector.toml.j2
        dest: /etc/vector/vector.toml
        mode: "0644"
      notify: Restart Vector

    - name: Enable and start Vector
      ansible.builtin.service:
        name: vector
        state: started
        enabled: true

- name: Install and Configure Lighthouse
  hosts: lighthouse
  become: true
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Install Node.js and npm
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Clone Lighthouse repository
      ansible.builtin.git:
        repo: "{{ lighthouse_repo }}"
        dest: /opt/lighthouse
        version: "{{ lighthouse_version }}"

    - name: Install Lighthouse dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /opt/lighthouse

    - name: Copy Nginx config for Lighthouse
      ansible.builtin.template:
        src: templates/lighthouse/nginx.conf.j2
        dest: /etc/nginx/sites-available/lighthouse
        mode: "0644"
      notify: Restart Nginx

    - name: Enable Nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/lighthouse
        dest: /etc/nginx/sites-enabled/lighthouse
        state: link

    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true