---
- name: Deploy ClickHouse, Vector, Lighthouse
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install common dependencies (curl, gnupg, etc.)
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: true

- name: Install Clickhouse
  tags: clickhouse
  hosts: clickhouse
  become: true
  roles: 
    - clickhouse
  tasks:
    - name: Create Clickhouse table
      ansible.builtin.command: clickhouse-client -q 'CREATE TABLE IF NOT EXISTS logs.{{ all_clickhouse_table }} (message String) ENGINE = MergeTree() ORDER BY tuple();'
      register: create_table
      failed_when: create_table.rc != 0 and create_table.rc != 82
      changed_when: create_table.rc == 0

- name: Install Vector
  tags: vector
  hosts: vector
  become: true
  roles: 
    - vector

- name: Install and Configure Lighthouse
  tags: lighthouse
  hosts: lighthouse
  become: true
  roles: 
    - lighthouse