services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    tty: true # Обеспечивает интерактивный TTY
    stdin_open: true # Позволяет держать контейнер открытым
    command: [ "tail", "-f", "/dev/null" ] # Бесконечная команда для поддержания работы
    networks:
      - app_net

  centos7:
    image: dokken/centos-stream-9
    container_name: centos7
    tty: true
    stdin_open: true
    command: [ "tail", "-f", "/dev/null" ]
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
