---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Install dependencies (apt-transport-https, ca-certificates, gnupg)
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Add ClickHouse GPG key
      ansible.builtin.apt_key:
        url: "https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key"
        state: present
  
    - name: Add ClickHouse repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.clickhouse.com/deb stable main"
        state: present
        filename: clickhouse.list

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install ClickHouse packages
      ansible.builtin.apt:
        name: "{{ clickhouse_packages }}"
        state: present
        force_apt_get: yes

    - name: Ensure ClickHouse service is enabled and started
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: yes

    - name: Verify ClickHouse is running
      ansible.builtin.command: clickhouse-client --query "SELECT version()"
      register: clickhouse_version_check
      ignore_errors: yes

    - name: Display ClickHouse version
      ansible.builtin.debug:
        var: clickhouse_version_check.stdout

    - name: Flush handlers
      meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
