---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

ansible_user: "ubuntu"
ansible_ssh_private_key_file: "/home/glubuchik/.ssh/aglubuchik"
